name: Build, Test, and Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Type check frontend
      run: |
        cd frontend
        npm run type-check
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build

  test-backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todo_db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup test database
      run: |
        cd backend
        export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/todo_db_test
        python setup_db.py
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todo_db_test
    
    - name: Run backend tests (placeholder)
      run: |
        cd backend
        echo "Backend tests would run here"
        python -c "import app; print('Backend imports successfully')"
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todo_db_test

  deploy:
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Deploy Credentials
      run: |
        if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
          echo "::error::RENDER_API_KEY secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.RENDER_BACKEND_SERVICE_ID }}" ]; then
          echo "::error::RENDER_BACKEND_SERVICE_ID secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.RENDER_FRONTEND_SERVICE_ID }}" ]; then
          echo "::error::RENDER_FRONTEND_SERVICE_ID secret is not set"
          exit 1
        fi
        echo "✅ All required secrets are present"
    
    - name: Deploy Backend to Render
      id: deploy-backend
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
      continue-on-error: true
    
    - name: Check Backend Deploy Status
      run: |
        if [ "${{ steps.deploy-backend.outcome }}" == "failure" ]; then
          echo "::error::Backend deployment failed. Check Render dashboard for details."
          echo "::error::Possible causes: Invalid API key, service ID not found, or deployment timeout"
          exit 1
        fi
        echo "✅ Backend deployment completed successfully"
    
    - name: Deploy Frontend to Render
      id: deploy-frontend
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
      continue-on-error: true
    
    - name: Check Frontend Deploy Status
      run: |
        if [ "${{ steps.deploy-frontend.outcome }}" == "failure" ]; then
          echo "::error::Frontend deployment failed. Check Render dashboard for details."
          echo "::error::Possible causes: Invalid API key, service ID not found, or deployment timeout"
          exit 1
        fi
        echo "✅ Frontend deployment completed successfully"
    
    - name: Deployment Summary
      if: always()
      run: |
        echo "## Deployment Summary"
        echo "Backend: ${{ steps.deploy-backend.outcome == 'success' && '✅ Success' || '❌ Failed' }}"
        echo "Frontend: ${{ steps.deploy-frontend.outcome == 'success' && '✅ Success' || '❌ Failed' }}"
        if [ "${{ steps.deploy-backend.outcome }}" == "failure" ] || [ "${{ steps.deploy-frontend.outcome }}" == "failure" ]; then
          echo "::error::One or more deployments failed. Check the logs above for details."
          exit 1
        fi